CC = g++
prog: connections.o game.o board.o piece.o 
	$(CC) connections.o game.o board.o piece.o -Wall -Werror -pedantic -o connections
connections.o: connections.cpp game.h
	$(CC) -Wall -Werror -pedantic -c connections.cpp
game.o: game.cpp game.h board.h piece.h move.h point.h player.h
	$(CC) -Wall -Werror -pedantic -c game.cpp
board.o: board.cpp board.h piece.h move.h point.h player.h
	$(CC) -Wall -Werror -pedantic -c board.cpp
piece.o: piece.cpp piece.h board.h move.h point.h player.h
	$(CC) -Wall -Werror -pedantic -c piece.cpp
